# =========================
# DOCKER COMPOSE PROFILE
# =========================

# Eureka - Docker container hostname
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
eureka.instance.prefer-ip-address=false
eureka.instance.hostname=api-gateway

# Logging
logging.level.com.example.api_gateway=INFO
